apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: orcamento-backend
  namespace: orcamento
spec:
  ingressClassName: nginx
  rules:
  - host: api.orcamento.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: orcamento-backend
            port:
              number: 8045
